name: Build site
on:
  push:

jobs:
  build:
    name: Build and deploy site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - run: pnpm build --env PUBLIC_PATH=/SimplerDays/build/

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
